import type { QuestionDatabase } from '../types';

export const questionDatabase: QuestionDatabase = {
  projectTypes: [
    { id: 'deck', label: 'Deck', description: 'New build, repair, or resurface', icon: 'Layers', calculatorId: 'deck' },
    { id: 'fence', label: 'Fence', description: 'Wood, vinyl, or metal fencing', icon: 'Fence', calculatorId: 'fence' },
    { id: 'kitchen', label: 'Kitchen', description: 'Full or partial kitchen remodel', icon: 'ChefHat', calculatorId: 'kitchen' },
    { id: 'bathroom', label: 'Bathroom', description: 'Full or partial bath remodel', icon: 'Bath', calculatorId: 'bathroom' },
    { id: 'ramp', label: 'Accessibility Ramp', description: 'Wheelchair ramp installation', icon: 'PersonStanding', calculatorId: 'ramp' },
    { id: 'accessibility-mod', label: 'Accessibility Modifications', description: 'Grab bars, door widening, threshold ramps', icon: 'Accessibility', calculatorId: 'accessibility-mod' },
    { id: 'accessibility', label: 'Accessibility (general)', description: 'Ramps, grab bars, wider doorways', icon: 'Accessibility', calculatorId: 'accessibility' },
    { id: 'porch', label: 'Porch', description: 'New porch or rebuild', icon: 'Home', calculatorId: 'porch' },
    { id: 'patio', label: 'Patio', description: 'Paver, concrete, or stamped patio', icon: 'Trees', calculatorId: 'patio' },
    { id: 'general-remodel', label: 'General Remodel', description: 'Basement, garage, or whole-room remodel', icon: 'Blocks', calculatorId: 'general-remodel' },
    { id: 'repair', label: 'Repairs', description: 'Drywall, flooring, paint, fixture repairs', icon: 'Wrench', calculatorId: 'repair' },
    { id: 'roofing', label: 'Roofing', description: 'Roof replacement and repair', icon: 'Home', calculatorId: 'roofing' },
    { id: 'siding', label: 'Siding', description: 'Siding installation and replacement', icon: 'Layers', calculatorId: 'siding' },
    { id: 'windows', label: 'Windows', description: 'Window replacement', icon: 'Square', calculatorId: 'windows' },
    { id: 'custom', label: 'Custom Project', description: 'Something unique? Tell us about it', icon: 'Sparkles', calculatorId: 'custom' },
  ],
  questions: [
    // ── Section 1: Project basics ──
    {
      id: 'projectType',
      step: 1,
      title: 'What are you building?',
      description: 'Pick a project type to get started.',
      inputType: 'select',
      bucket: 'project',
      options: [
        { value: 'deck', label: 'Deck', description: 'New build, repair, or resurface' },
        { value: 'fence', label: 'Fence', description: 'Wood, vinyl, or metal fencing' },
        { value: 'kitchen', label: 'Kitchen', description: 'Full or partial kitchen remodel' },
        { value: 'bathroom', label: 'Bathroom', description: 'Full or partial bath remodel' },
        { value: 'ramp', label: 'Accessibility Ramp', description: 'Wheelchair ramp installation' },
        { value: 'accessibility-mod', label: 'Accessibility Modifications', description: 'Grab bars, door widening, threshold ramps' },
        { value: 'accessibility', label: 'Accessibility (general)', description: 'Ramps, grab bars, wider doorways' },
        { value: 'porch', label: 'Porch', description: 'New porch or rebuild' },
        { value: 'patio', label: 'Patio', description: 'Paver, concrete, or stamped patio' },
        { value: 'general-remodel', label: 'General Remodel', description: 'Basement, garage, or whole-room remodel' },
        { value: 'repair', label: 'Repairs', description: 'Drywall, flooring, paint, fixture repairs' },
        { value: 'roofing', label: 'Roofing', description: 'Roof replacement and repair' },
        { value: 'siding', label: 'Siding', description: 'Siding installation and replacement' },
        { value: 'windows', label: 'Windows', description: 'Window replacement' },
        { value: 'custom', label: 'Custom Project', description: 'Something unique? Tell us about it' },
      ],
      validation: { required: true },
    },
    {
      id: 'projectScope',
      step: 2,
      title: 'Is this a new build or a renovation?',
      description: 'Tell us whether we are starting from scratch or working with an existing structure.',
      inputType: 'radio',
      bucket: 'project',
      condition: (a) => a.projectType !== undefined,
      options: [
        { value: 'new', label: 'New build', description: 'Starting from scratch — no existing structure' },
        { value: 'renovation', label: 'Renovation / remodel', description: 'Updating or replacing an existing structure' },
        { value: 'repair', label: 'Repair only', description: 'Fixing damage or wear on an existing structure' },
      ],
      validation: { required: true },
    },
    {
      id: 'region',
      step: 3,
      title: 'Where is the project located?',
      description: 'Pricing varies slightly by region.',
      inputType: 'radio',
      bucket: 'location',
      condition: (a) => a.projectType !== undefined,
      options: [
        { value: 'DE', label: 'Delaware' },
        { value: 'PA', label: 'Pennsylvania' },
      ],
      validation: { required: true },
    },
    {
      id: 'zipCode',
      step: 4,
      title: 'What is the ZIP code?',
      description: 'Helps us confirm your area and pull the right permit info.',
      inputType: 'text',
      bucket: 'location',
      placeholder: 'e.g. 19901',
      condition: (a) => a.region !== undefined,
      validation: { required: true, maxLength: 10 },
    },
    {
      id: 'propertyType',
      step: 5,
      title: 'What kind of property is it?',
      inputType: 'radio',
      bucket: 'location',
      condition: (a) => a.region !== undefined,
      options: [
        { value: 'single-family', label: 'Single-family home' },
        { value: 'townhouse', label: 'Townhouse' },
        { value: 'condo', label: 'Condo / apartment' },
        { value: 'commercial', label: 'Commercial property' },
      ],
      validation: { required: true },
    },

    // ── Section 2: Measurements ──
    {
      id: 'dimensions',
      step: 6,
      title: 'What are the measurements?',
      description: 'Enter the length and width in feet and inches. We will calculate the square footage for you.',
      inputType: 'dimensions',
      bucket: 'measurements',
      condition: (a) => a.projectType !== undefined,
      validation: { required: true },
    },
    // ── Deck-specific details ──
    {
      id: 'deckHeight',
      step: 7,
      title: 'How high off the ground is the deck?',
      description: 'Affects footing depth, railing requirements, and stair count.',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'deck',
      options: [
        { value: 'ground-level', label: 'Ground level (under 30")', description: 'No railing required by code' },
        { value: 'low', label: 'Low (30"–48")', description: 'Railing required' },
        { value: 'mid', label: 'Elevated (48"–96")', description: 'Railing + stairs required' },
        { value: 'high', label: 'High (over 96")', description: 'Engineered footings, stairs, landing' },
      ],
      validation: { required: true },
    },
    {
      id: 'deckAttachment',
      step: 7,
      title: 'How will the deck attach to the house?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'deck',
      options: [
        { value: 'attached', label: 'Attached to house', description: 'Ledger board against house' },
        { value: 'freestanding', label: 'Freestanding', description: 'Self-supported, not touching house' },
        { value: 'not-sure', label: 'Not sure', description: 'Jeremiah will advise' },
      ],
      validation: { required: true },
    },
    {
      id: 'deckRailingLength',
      step: 7,
      title: 'How many linear feet of railing?',
      description: 'Perimeter edges that need railing. Enter 0 if none.',
      inputType: 'number',
      bucket: 'measurements',
      unit: 'ln ft',
      placeholder: 'e.g. 40',
      condition: (a) => a.projectType === 'deck',
      validation: { required: true, min: 0, max: 400 },
    },
    {
      id: 'deckStairs',
      step: 7,
      title: 'How many stair steps?',
      description: 'Count individual steps (not staircases). Enter 0 if none.',
      inputType: 'number',
      bucket: 'measurements',
      unit: 'steps',
      placeholder: 'e.g. 4',
      condition: (a) => a.projectType === 'deck',
      validation: { required: true, min: 0, max: 30 },
    },

    // ── Fence-specific details ──
    {
      id: 'fenceLength',
      step: 7,
      title: 'What is the total fence length?',
      description: 'Total linear feet of the fence line (not including gates).',
      inputType: 'number',
      bucket: 'measurements',
      unit: 'ln ft',
      placeholder: 'e.g. 120',
      condition: (a) => a.projectType === 'fence',
      validation: { required: true, min: 10, max: 2000 },
    },
    {
      id: 'fenceHeight',
      step: 7,
      title: 'How tall should the fence be?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'fence',
      options: [
        { value: '4ft', label: '4 ft', description: 'Front yard standard' },
        { value: '6ft', label: '6 ft', description: 'Backyard privacy standard' },
        { value: '8ft', label: '8 ft', description: 'Max privacy / commercial' },
      ],
      validation: { required: true },
    },
    {
      id: 'fenceGates',
      step: 7,
      title: 'How many gates?',
      description: 'Walk gates and/or double drive gates.',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'fence',
      options: [
        { value: 'none', label: 'No gates' },
        { value: 'walk-only', label: '1+ walk gates' },
        { value: 'double-only', label: '1+ double drive gates' },
        { value: 'both', label: 'Both walk and drive gates' },
      ],
      validation: { required: true },
    },
    {
      id: 'fenceLayout',
      step: 7,
      title: 'What is the terrain like?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'fence',
      options: [
        { value: 'flat', label: 'Flat and level', description: 'Straightforward install' },
        { value: 'slope', label: 'Sloped or uneven', description: 'Stepped or racked fencing' },
        { value: 'mixed', label: 'Mixed terrain', description: 'Some flat, some slope' },
      ],
      validation: { required: true },
    },

    // ── Kitchen-specific details ──
    {
      id: 'kitchenCounterMaterial',
      step: 7,
      title: 'What countertop material do you want?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'kitchen',
      options: [
        { value: 'laminate', label: 'Laminate', description: 'Budget-friendly' },
        { value: 'quartz', label: 'Quartz', description: 'Durable, low maintenance' },
        { value: 'granite', label: 'Granite', description: 'Natural stone' },
        { value: 'marble', label: 'Marble / quartzite', description: 'Premium natural stone' },
        { value: 'butcher-block', label: 'Butcher block', description: 'Warm, natural wood' },
      ],
      validation: { required: true },
    },
    {
      id: 'kitchenAppliances',
      step: 7,
      title: 'Are appliances being replaced?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'kitchen',
      options: [
        { value: 'keep', label: 'Keep existing appliances' },
        { value: 'replace-standard', label: 'Replace with standard package' },
        { value: 'replace-premium', label: 'Replace with premium package' },
        { value: 'not-sure', label: 'Not sure yet' },
      ],
      validation: { required: true },
    },
    {
      id: 'kitchenLayoutChange',
      step: 7,
      title: 'Are you changing the kitchen layout?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'kitchen',
      options: [
        { value: 'same', label: 'Same layout', description: 'Cabinets stay in same footprint' },
        { value: 'minor', label: 'Minor changes', description: 'Move an island or peninsula' },
        { value: 'major', label: 'Major reconfiguration', description: 'Move sink, appliances, or walls' },
      ],
      validation: { required: true },
    },

    // ── Bathroom-specific details ──
    {
      id: 'bathroomType',
      step: 7,
      title: 'What type of bathroom is it?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'bathroom',
      options: [
        { value: 'full', label: 'Full bath', description: 'Tub and/or shower + toilet + vanity' },
        { value: 'half', label: 'Half bath / powder room', description: 'Toilet + vanity only' },
        { value: 'master', label: 'Master bath', description: 'Large, may include double vanity + soaking tub' },
      ],
      validation: { required: true },
    },
    {
      id: 'bathroomShowerType',
      step: 7,
      title: 'What shower or tub do you want?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'bathroom',
      options: [
        { value: 'tub-shower-combo', label: 'Tub/shower combo', description: 'Standard tub with shower' },
        { value: 'walk-in-shower', label: 'Walk-in shower', description: 'No tub, tile or acrylic' },
        { value: 'soaking-tub', label: 'Soaking / freestanding tub', description: 'Separate tub + shower' },
        { value: 'roll-in', label: 'Roll-in shower', description: 'Curbless, accessible' },
      ],
      validation: { required: true },
    },
    {
      id: 'bathroomPlumbingMove',
      step: 7,
      title: 'Are plumbing fixtures moving?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'bathroom',
      options: [
        { value: 'no-move', label: 'No, staying in place' },
        { value: 'minor-move', label: 'Minor moves', description: 'Shift toilet or vanity slightly' },
        { value: 'major-move', label: 'Major relocation', description: 'Move tub, shower, or drain lines' },
      ],
      validation: { required: true },
    },

    // ── Ramp-specific details ──
    {
      id: 'rampRise',
      step: 7,
      title: 'What is the total rise (height to reach)?',
      description: 'Height from ground to the doorway or landing.',
      inputType: 'number',
      bucket: 'measurements',
      unit: 'inches',
      placeholder: 'e.g. 24',
      condition: (a) => a.projectType === 'ramp',
      validation: { required: true, min: 2, max: 120 },
    },
    {
      id: 'rampEntryLocation',
      step: 7,
      title: 'Where does the ramp lead?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'ramp',
      options: [
        { value: 'front-door', label: 'Front door' },
        { value: 'back-door', label: 'Back / side door' },
        { value: 'garage', label: 'Garage entry' },
        { value: 'porch-deck', label: 'To porch or deck' },
      ],
      validation: { required: true },
    },
    {
      id: 'rampUserType',
      step: 7,
      title: 'Who will use the ramp?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'ramp',
      options: [
        { value: 'wheelchair', label: 'Wheelchair user', description: '1:12 slope, ADA-compliant' },
        { value: 'walker', label: 'Walker / cane user', description: 'Gentler slope preferred' },
        { value: 'both', label: 'Multiple users' },
      ],
      validation: { required: true },
    },

    // ── Accessibility-mod-specific details ──
    {
      id: 'accessModLocation',
      step: 7,
      title: 'Where are the modifications needed?',
      inputType: 'checkbox',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'accessibility-mod' || a.projectType === 'accessibility',
      options: [
        { value: 'bathroom', label: 'Bathroom' },
        { value: 'kitchen', label: 'Kitchen' },
        { value: 'entry', label: 'Entry / doorway' },
        { value: 'hallway', label: 'Hallway' },
        { value: 'stairs', label: 'Stairs' },
        { value: 'bedroom', label: 'Bedroom' },
      ],
      validation: { required: true },
    },

    // ── Porch-specific details ──
    {
      id: 'porchHeight',
      step: 7,
      title: 'How high off the ground is the porch?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'porch',
      options: [
        { value: 'ground-level', label: 'Ground level (under 12")' },
        { value: 'low', label: 'Low (12"–36")' },
        { value: 'elevated', label: 'Elevated (over 36")' },
      ],
      validation: { required: true },
    },
    {
      id: 'porchColumns',
      step: 7,
      title: 'How many support columns?',
      description: 'Decorative or structural columns. Enter 0 if none.',
      inputType: 'number',
      bucket: 'measurements',
      unit: 'columns',
      placeholder: 'e.g. 2',
      condition: (a) => a.projectType === 'porch',
      validation: { required: true, min: 0, max: 20 },
    },
    {
      id: 'porchSteps',
      step: 7,
      title: 'How many steps lead up to the porch?',
      inputType: 'number',
      bucket: 'measurements',
      unit: 'steps',
      placeholder: 'e.g. 3',
      condition: (a) => a.projectType === 'porch',
      validation: { required: true, min: 0, max: 20 },
    },

    // ── Patio-specific details ──
    {
      id: 'patioBaseCondition',
      step: 7,
      title: 'What is the ground like now?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'patio',
      options: [
        { value: 'lawn', label: 'Lawn / grass', description: 'Needs excavation and base prep' },
        { value: 'bare-soil', label: 'Bare soil', description: 'Some grading needed' },
        { value: 'old-surface', label: 'Existing concrete / pavers', description: 'Removal required first' },
      ],
      validation: { required: true },
    },
    {
      id: 'patioDrainage',
      step: 7,
      title: 'Any drainage concerns?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'patio',
      options: [
        { value: 'none', label: 'No known issues' },
        { value: 'some', label: 'Some pooling or runoff', description: 'May need grading or drain' },
        { value: 'significant', label: 'Significant drainage issues', description: 'Needs proper drainage solution' },
        { value: 'not-sure', label: 'Not sure' },
      ],
      validation: { required: true },
    },

    // ── General-remodel-specific details ──
    {
      id: 'remodelRoomType',
      step: 7,
      title: 'What room or space is being remodeled?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'general-remodel',
      options: [
        { value: 'basement', label: 'Basement' },
        { value: 'garage', label: 'Garage' },
        { value: 'bedroom', label: 'Bedroom' },
        { value: 'living-room', label: 'Living room' },
        { value: 'dining-room', label: 'Dining room' },
        { value: 'office', label: 'Home office' },
        { value: 'whole-floor', label: 'Entire floor' },
        { value: 'other', label: 'Other' },
      ],
      validation: { required: true },
    },
    {
      id: 'remodelElectrical',
      step: 7,
      title: 'Does the electrical need updating?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'general-remodel',
      options: [
        { value: 'no', label: 'No electrical work' },
        { value: 'minor', label: 'Minor updates', description: 'A few new outlets or lights' },
        { value: 'major', label: 'Major update', description: 'New panel or full rewiring' },
        { value: 'not-sure', label: 'Not sure' },
      ],
      validation: { required: true },
    },

    // ── Repair-specific details ──
    {
      id: 'repairUrgency',
      step: 7,
      title: 'How urgent is the repair?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'repair',
      options: [
        { value: 'emergency', label: 'Emergency', description: 'Active leak, damage, or safety issue' },
        { value: 'soon', label: 'Needs attention soon' },
        { value: 'planning', label: 'Planning ahead' },
      ],
      validation: { required: true },
    },
    {
      id: 'repairLocation',
      step: 7,
      title: 'Where is the repair needed?',
      inputType: 'checkbox',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'repair',
      options: [
        { value: 'interior', label: 'Interior' },
        { value: 'exterior', label: 'Exterior' },
        { value: 'kitchen', label: 'Kitchen' },
        { value: 'bathroom', label: 'Bathroom' },
        { value: 'ceiling', label: 'Ceiling' },
        { value: 'walls', label: 'Walls' },
        { value: 'floor', label: 'Floor' },
      ],
      validation: { required: true },
    },

    // ── Roofing-specific details ──
    {
      id: 'roofingPitch',
      step: 7,
      title: 'What is the roof pitch (steepness)?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'roofing',
      options: [
        { value: 'flat', label: 'Flat / low slope', description: 'Walkable, under 3:12' },
        { value: 'standard', label: 'Standard pitch', description: '4:12 to 8:12, typical' },
        { value: 'steep', label: 'Steep pitch', description: 'Over 8:12, requires safety equipment' },
        { value: 'not-sure', label: 'Not sure' },
      ],
      validation: { required: true },
    },
    {
      id: 'roofingLayers',
      step: 7,
      title: 'How many layers of roofing are on now?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'roofing',
      options: [
        { value: '1', label: 'One layer' },
        { value: '2-plus', label: 'Two or more layers', description: 'Tear-off required by code' },
        { value: 'none', label: 'New construction (no roof yet)' },
        { value: 'not-sure', label: 'Not sure' },
      ],
      validation: { required: true },
    },
    {
      id: 'roofingAge',
      step: 7,
      title: 'How old is the current roof?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'roofing',
      options: [
        { value: 'new', label: 'Less than 10 years' },
        { value: 'aging', label: '10–20 years' },
        { value: 'old', label: 'Over 20 years' },
        { value: 'not-sure', label: 'Not sure' },
      ],
      validation: { required: true },
    },

    // ── Siding-specific details ──
    {
      id: 'sidingStories',
      step: 7,
      title: 'How many stories is the building?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'siding',
      options: [
        { value: '1', label: 'Single story' },
        { value: '2', label: 'Two stories' },
        { value: '3-plus', label: 'Three or more' },
      ],
      validation: { required: true },
    },
    {
      id: 'sidingCurrentCondition',
      step: 7,
      title: 'What is the current siding condition?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'siding',
      options: [
        { value: 'good', label: 'Good — remove and replace' },
        { value: 'damaged', label: 'Damaged — may have rot or water issues' },
        { value: 'none', label: 'New construction (no siding yet)' },
        { value: 'not-sure', label: 'Not sure' },
      ],
      validation: { required: true },
    },

    // ── Windows-specific details ──
    {
      id: 'windowStyles',
      step: 7,
      title: 'What window style(s) do you want?',
      inputType: 'checkbox',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'windows',
      options: [
        { value: 'double-hung', label: 'Double-hung', description: 'Two sashes, slides up/down' },
        { value: 'casement', label: 'Casement', description: 'Cranks outward' },
        { value: 'sliding', label: 'Sliding', description: 'Slides sideways' },
        { value: 'picture', label: 'Picture / fixed', description: 'Does not open' },
        { value: 'bay-bow', label: 'Bay or bow', description: 'Projects outward' },
        { value: 'egress', label: 'Egress (basement)', description: 'Code-required exit size' },
      ],
      validation: { required: true },
    },
    {
      id: 'windowRot',
      step: 7,
      title: 'Is there any rot around the window frames?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'windows',
      options: [
        { value: 'no', label: 'No rot visible' },
        { value: 'some', label: 'Some rot', description: 'May need full-frame replacement' },
        { value: 'not-sure', label: 'Not sure — needs inspection' },
      ],
      validation: { required: true },
    },

    // ── Custom-project-specific details ──
    {
      id: 'customCategory',
      step: 7,
      title: 'What category best describes your project?',
      inputType: 'radio',
      bucket: 'measurements',
      condition: (a) => a.projectType === 'custom',
      options: [
        { value: 'built-in', label: 'Built-ins / cabinetry', description: 'Bookshelves, entertainment center, etc.' },
        { value: 'structural', label: 'Structural / framing', description: 'Walls, openings, supports' },
        { value: 'outdoor', label: 'Outdoor structure', description: 'Gazebo, shed, pergola, etc.' },
        { value: 'finish', label: 'Finish work', description: 'Trim, doors, molding' },
        { value: 'other', label: 'Other', description: 'Does not fit the above' },
      ],
      validation: { required: true },
    },

    // ── Section 3: Materials (project-specific) ──
    {
      id: 'deckMaterial',
      step: 8,
      title: 'What decking material do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'deck',
      options: [
        { value: 'pressure-treated', label: 'Pressure-treated wood', description: 'Budget-friendly, 10–15 year lifespan' },
        { value: 'cedar', label: 'Cedar', description: 'Natural beauty, 15–20 year lifespan' },
        { value: 'composite', label: 'Composite', description: 'Low maintenance, 25+ year lifespan' },
        { value: 'pvc', label: 'PVC / Trex', description: 'Premium low-maintenance, 30+ year lifespan' },
        { value: 'exotic-hardwood', label: 'Exotic hardwood', description: 'Ipe, tigerwood — premium look' },
      ],
      validation: { required: true },
    },
    {
      id: 'fenceMaterial',
      step: 8,
      title: 'What fencing material do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'fence',
      options: [
        { value: 'cedar', label: 'Cedar wood', description: 'Natural look, needs periodic sealing' },
        { value: 'pressure-treated', label: 'Pressure-treated wood', description: 'Budget-friendly option' },
        { value: 'vinyl', label: 'Vinyl / PVC', description: 'Low maintenance, long-lasting' },
        { value: 'aluminum', label: 'Aluminum', description: 'Elegant, rust-proof' },
        { value: 'chain-link', label: 'Chain link', description: 'Economical, secure' },
        { value: 'wrought-iron', label: 'Wrought iron', description: 'Premium, ornamental' },
      ],
      validation: { required: true },
    },
    {
      id: 'kitchenMaterial',
      step: 8,
      title: 'What cabinet and counter material do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'kitchen',
      options: [
        { value: 'stock-laminate', label: 'Stock cabinets + laminate counters', description: 'Budget-friendly, builder-grade' },
        { value: 'semi-custom-quartz', label: 'Semi-custom cabinets + quartz', description: 'Upgraded quality and finish' },
        { value: 'custom-quartz', label: 'Custom cabinets + quartz', description: 'Premium fit and finish' },
        { value: 'custom-marble', label: 'Custom cabinets + marble/quartzite', description: 'Top-tier materials' },
      ],
      validation: { required: true },
    },
    {
      id: 'bathroomMaterial',
      step: 8,
      title: 'What tile and fixture quality do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'bathroom',
      options: [
        { value: 'standard-tile', label: 'Standard tile + builder fixtures', description: 'Budget-friendly, functional' },
        { value: 'upgraded-tile', label: 'Upgraded tile + mid-range fixtures', description: 'Better quality and style' },
        { value: 'premium-tile', label: 'Premium tile + designer fixtures', description: 'High-end look and feel' },
        { value: 'luxury-tile', label: 'Luxury tile + premium fixtures', description: 'Top-tier materials and brands' },
      ],
      validation: { required: true },
    },
    {
      id: 'accessibilityMaterial',
      step: 8,
      title: 'What material do you prefer for the ramp or modifications?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'accessibility',
      options: [
        { value: 'wood-ramp', label: 'Wood ramp', description: 'Treated lumber, budget-friendly' },
        { value: 'aluminum-ramp', label: 'Aluminum ramp', description: 'Low maintenance, modular' },
        { value: 'concrete-ramp', label: 'Concrete ramp', description: 'Permanent, durable' },
        { value: 'grab-bars-only', label: 'Grab bars / door widening only', description: 'No ramp needed' },
      ],
      validation: { required: true },
    },
    {
      id: 'porchMaterial',
      step: 8,
      title: 'What type of porch do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'porch',
      options: [
        { value: 'porch-basic', label: 'Open porch', description: 'No screens or roof' },
        { value: 'porch-screened', label: 'Screened porch', description: 'Screened enclosure' },
        { value: 'porch-covered', label: 'Covered porch', description: 'With roof structure' },
      ],
      validation: { required: true },
    },
    {
      id: 'patioMaterial',
      step: 8,
      title: 'What patio surface do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'patio',
      options: [
        { value: 'paver', label: 'Paver stones', description: 'Premium look, repairable' },
        { value: 'concrete', label: 'Concrete', description: 'Durable, economical' },
        { value: 'stamped', label: 'Stamped concrete', description: 'Decorative, textured finish' },
      ],
      validation: { required: true },
    },
    {
      id: 'remodelTier',
      step: 8,
      title: 'What level of finishes do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'general-remodel',
      options: [
        { value: 'remodel-essential', label: 'Essential', description: 'Basic finishes, functional space' },
        { value: 'remodel-mid', label: 'Mid-range', description: 'Upgraded finishes, drywall, trim' },
        { value: 'remodel-premium', label: 'Premium', description: 'High-end finishes, custom details' },
      ],
      validation: { required: true },
    },
    {
      id: 'repairType',
      step: 8,
      title: 'What type of repair do you need?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'repair',
      options: [
        { value: 'drywall', label: 'Drywall repair', description: 'Patching, replacement' },
        { value: 'flooring', label: 'Flooring repair', description: 'Board, tile, or panel replacement' },
        { value: 'paint', label: 'Painting', description: 'Interior or exterior' },
        { value: 'fixture', label: 'Fixture replacement', description: 'Light, faucet, hardware' },
        { value: 'general', label: 'General handyman', description: 'Multi-item or unclear scope' },
      ],
      validation: { required: true },
    },
    {
      id: 'roofingMaterial',
      step: 8,
      title: 'What roofing material do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'roofing',
      options: [
        { value: 'asphalt', label: 'Architectural asphalt', description: 'Most common, 30-yr warranty' },
        { value: 'metal', label: 'Standing seam metal', description: '50-yr lifespan' },
        { value: 'rubber', label: 'Rubber / EPDM', description: 'For flat roofs' },
        { value: 'slate', label: 'Slate or tile', description: 'Premium, 75+ yr' },
      ],
      validation: { required: true },
    },
    {
      id: 'sidingMaterial',
      step: 8,
      title: 'What siding material do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'siding',
      options: [
        { value: 'vinyl-siding', label: 'Vinyl', description: 'Budget-friendly, low maintenance' },
        { value: 'fiber-cement', label: 'Fiber cement (Hardie)', description: 'Durable, wood-like look' },
        { value: 'cedar-siding', label: 'Cedar', description: 'Natural beauty, needs upkeep' },
        { value: 'stucco', label: 'Stucco', description: 'Long-lasting' },
      ],
      validation: { required: true },
    },
    {
      id: 'windowsFrame',
      step: 8,
      title: 'What window frame material do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'windows',
      options: [
        { value: 'vinyl', label: 'Vinyl', description: 'Affordable, low maintenance' },
        { value: 'fiberglass', label: 'Fiberglass', description: 'Stronger, paintable' },
        { value: 'wood-clad', label: 'Wood-clad', description: 'Premium look' },
      ],
      validation: { required: true },
    },
    {
      id: 'windowsGlass',
      step: 8,
      title: 'What glass package do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'windows',
      options: [
        { value: 'double', label: 'Double-pane, Low-E', description: 'Standard efficient' },
        { value: 'triple', label: 'Triple-pane, Low-E', description: 'Maximum efficiency' },
      ],
      validation: { required: true },
    },
    {
      id: 'windowsInstallType',
      step: 8,
      title: 'What installation type do you want?',
      inputType: 'radio',
      bucket: 'materials',
      condition: (a) => a.projectType === 'windows',
      options: [
        { value: 'full-frame', label: 'Full-frame', description: 'Complete tear-out' },
        { value: 'insert', label: 'Insert (pocket)', description: 'Reuse existing frame' },
      ],
      validation: { required: true },
    },

    // ── Section 4: Project-specific scope ──
    {
      id: 'deckFeatures',
      step: 9,
      title: 'What deck features do you want?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'deck',
      options: [
        { value: 'railings', label: 'Railings' },
        { value: 'stairs', label: 'Stairs' },
        { value: 'skirting', label: 'Skirting / lattice' },
        { value: 'built-in-seating', label: 'Built-in seating' },
        { value: 'planter-boxes', label: 'Planter boxes' },
        { value: 'lighting', label: 'Low-voltage lighting' },
        { value: 'pergola', label: 'Pergola or shade structure' },
        { value: 'multi-level', label: 'Multi-level design' },
      ],
    },
    {
      id: 'fenceFeatures',
      step: 9,
      title: 'What fence features do you want?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'fence',
      options: [
        { value: 'gate', label: 'Walk gate' },
        { value: 'double-gate', label: 'Double drive gate' },
        { value: 'post-caps', label: 'Decorative post caps' },
        { value: 'lattice-top', label: 'Lattice top' },
        { value: 'stain', label: 'Stain / seal' },
        { value: 'removal', label: 'Remove old fence' },
      ],
    },
    {
      id: 'kitchenScope',
      step: 9,
      title: 'What is included in the kitchen remodel?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'kitchen',
      options: [
        { value: 'cabinets', label: 'Replace cabinets' },
        { value: 'counters', label: 'Replace countertops' },
        { value: 'appliances', label: 'Replace appliances' },
        { value: 'sink-faucet', label: 'New sink and faucet' },
        { value: 'flooring', label: 'Replace flooring' },
        { value: 'backsplash', label: 'Backsplash' },
        { value: 'lighting', label: 'New lighting' },
        { value: 'wall-removal', label: 'Remove wall (open concept)' },
        { value: 'island', label: 'Add or expand island' },
        { value: 'pantry', label: 'Add pantry' },
      ],
    },
    {
      id: 'bathroomScope',
      step: 9,
      title: 'What is included in the bathroom remodel?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'bathroom',
      options: [
        { value: 'tub-shower', label: 'Replace tub or shower' },
        { value: 'tile-shower', label: 'Tile shower' },
        { value: 'vanity', label: 'Replace vanity' },
        { value: 'toilet', label: 'Replace toilet' },
        { value: 'flooring', label: 'Replace flooring' },
        { value: 'lighting', label: 'New lighting / vent fan' },
        { value: 'plumbing-move', label: 'Move plumbing locations' },
        { value: 'wall-removal', label: 'Remove wall' },
        { value: 'linen-storage', label: 'Add linen storage' },
        { value: 'heated-floor', label: 'Heated floor' },
      ],
    },
    {
      id: 'accessibilityScope',
      step: 9,
      title: 'What accessibility modifications do you need?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'accessibility' || a.projectType === 'accessibility-mod' || a.projectType === 'ramp',
      options: [
        { value: 'ramp', label: 'Wheelchair ramp' },
        { value: 'grab-bars', label: 'Grab bars' },
        { value: 'widen-doors', label: 'Widen doorways' },
        { value: 'lower-counters', label: 'Lower kitchen counters' },
        { value: 'roll-shower', label: 'Roll-in shower' },
        { value: 'handrails', label: 'Handrails for stairs' },
        { value: 'thresholds', label: 'Flush thresholds' },
        { value: 'stair-lift', label: 'Stair lift prep' },
      ],
    },
    {
      id: 'porchFeatures',
      step: 9,
      title: 'What porch features do you want?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'porch',
      options: [
        { value: 'roofing', label: 'Roof structure' },
        { value: 'columns', label: 'Support columns' },
        { value: 'railings', label: 'Railings' },
        { value: 'steps', label: 'Steps' },
        { value: 'skirting', label: 'Skirting' },
        { value: 'screened', label: 'Screen enclosure' },
      ],
    },
    {
      id: 'patioFeatures',
      step: 9,
      title: 'What patio features do you want?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'patio',
      options: [
        { value: 'fire-pit', label: 'Fire pit' },
        { value: 'seating-wall', label: 'Seating wall' },
        { value: 'lighting', label: 'Landscape lighting' },
        { value: 'pergola', label: 'Pergola overhead' },
        { value: 'removal', label: 'Remove old surface' },
      ],
    },
    {
      id: 'remodelScope',
      step: 9,
      title: 'What is included in the remodel?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'general-remodel',
      options: [
        { value: 'flooring', label: 'Replace flooring' },
        { value: 'drywall', label: 'New drywall' },
        { value: 'lighting', label: 'New lighting' },
        { value: 'plumbing-move', label: 'Move plumbing' },
        { value: 'wall-removal', label: 'Remove wall' },
        { value: 'insulation', label: 'Add insulation' },
        { value: 'built-in', label: 'Built-in shelving' },
      ],
    },
    {
      id: 'roofingFeatures',
      step: 9,
      title: 'What roofing features do you need?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'roofing',
      options: [
        { value: 'tearoff', label: 'Tear off old roof' },
        { value: 'leak', label: 'Leak inspection & repair' },
        { value: 'gutters', label: 'New gutters' },
        { value: 'skylight', label: 'Skylight installation' },
      ],
    },
    {
      id: 'sidingFeatures',
      step: 9,
      title: 'What siding features do you need?',
      description: 'Select all that apply.',
      inputType: 'checkbox',
      bucket: 'features',
      condition: (a) => a.projectType === 'siding',
      options: [
        { value: 'insulation', label: 'Insulated underlayment' },
        { value: 'trim', label: 'Replace trim & soffits' },
        { value: 'removal', label: 'Remove old siding' },
      ],
    },
    {
      id: 'windowsCount',
      step: 9,
      title: 'How many windows?',
      description: 'Count each window unit.',
      inputType: 'number',
      bucket: 'features',
      unit: 'windows',
      placeholder: 'e.g. 8',
      condition: (a) => a.projectType === 'windows',
      validation: { required: true, min: 1, max: 40 },
    },
    {
      id: 'customDescription',
      step: 9,
      title: 'Describe your custom project',
      description: 'Tell us what you envision. The more detail, the better we can prepare.',
      inputType: 'textarea',
      bucket: 'features',
      placeholder: 'e.g. Built-in bookshelves flanking a fireplace with hidden storage below...',
      condition: (a) => a.projectType === 'custom',
      validation: { required: true, maxLength: 2000 },
    },

    // ── Section 5: Site conditions ──
    {
      id: 'siteAccess',
      step: 10,
      title: 'How easy is site access?',
      description: 'Can a truck and tools get to the work area easily?',
      inputType: 'radio',
      bucket: 'site',
      condition: (a) => a.projectType !== undefined,
      options: [
        { value: 'easy', label: 'Easy', description: 'Paved, level, plenty of room' },
        { value: 'moderate', label: 'Moderate', description: 'Some stairs, narrow path, or slope' },
        { value: 'difficult', label: 'Difficult', description: 'Steep, tight, or requires carrying materials far' },
      ],
      validation: { required: true },
    },
    {
      id: 'existingCondition',
      step: 11,
      title: 'What condition is the existing area in?',
      inputType: 'radio',
      bucket: 'site',
      condition: (a) => a.projectScope === 'renovation' || a.projectScope === 'repair',
      options: [
        { value: 'good', label: 'Good', description: 'Structurally sound, minor wear' },
        { value: 'fair', label: 'Fair', description: 'Some damage, rot, or aging' },
        { value: 'poor', label: 'Poor', description: 'Significant damage, rot, or structural issues' },
        { value: 'unknown', label: 'Not sure', description: 'Needs inspection' },
      ],
      validation: { required: true },
    },
    {
      id: 'demolition',
      step: 12,
      title: 'Will demolition be needed?',
      description: 'Do we need to tear out anything before building?',
      inputType: 'boolean',
      bucket: 'site',
      condition: (a) => a.projectScope === 'renovation' || a.projectScope === 'repair',
      validation: { required: true },
    },

    // ── Section 6: Permits and timeline ──
    {
      id: 'permitsNeeded',
      step: 13,
      title: 'Do you need us to pull permits?',
      inputType: 'radio',
      bucket: 'permits',
      condition: (a) => a.projectType !== undefined,
      options: [
        { value: 'yes-handle', label: 'Yes, handle it for me', description: 'We handle all permits and inspections' },
        { value: 'yes-split', label: 'Yes, but I will pull them', description: 'You handle the paperwork' },
        { value: 'not-sure', label: 'Not sure', description: 'We will advise during the site visit' },
        { value: 'no', label: 'No permits needed' },
      ],
      validation: { required: true },
    },
    {
      id: 'timeline',
      step: 14,
      title: 'When would you like to start?',
      inputType: 'radio',
      bucket: 'timeline',
      condition: (a) => a.projectType !== undefined,
      options: [
        { value: 'asap', label: 'ASAP', description: 'Ready to go now' },
        { value: '1-3-months', label: '1–3 months' },
        { value: '3-6-months', label: '3–6 months' },
        { value: '6-12-months', label: '6–12 months' },
        { value: 'flexible', label: 'Flexible' },
      ],
      validation: { required: true },
    },
    {
      id: 'budgetRange',
      step: 15,
      title: 'What is your budget range?',
      description: 'This helps us tailor material recommendations to your budget.',
      inputType: 'radio',
      bucket: 'budget',
      condition: (a) => a.projectType !== undefined,
      options: [
        { value: 'under-5k', label: 'Under $5,000' },
        { value: '5k-10k', label: '$5,000 – $10,000' },
        { value: '10k-25k', label: '$10,000 – $25,000' },
        { value: '25k-50k', label: '$25,000 – $50,000' },
        { value: '50k-plus', label: '$50,000+' },
        { value: 'not-sure', label: 'Not sure yet' },
      ],
      validation: { required: true },
    },

    // ── Section 7: Photos and details ──
    {
      id: 'photos',
      step: 16,
      title: 'Upload photos of the area',
      description: 'Add pictures of the existing space, any damage, or inspiration photos. Up to 20 images.',
      inputType: 'file',
      bucket: 'photos',
      condition: (a) => a.projectType !== undefined,
      validation: { accept: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf'], maxSizeMb: 20 },
    },
    {
      id: 'specialRequests',
      step: 17,
      title: 'Anything else we should know?',
      description: 'Special requests, concerns, design ideas, or anything else you want us to consider.',
      inputType: 'textarea',
      bucket: 'details',
      placeholder: 'Tell us about any special requirements, design preferences, or concerns...',
      condition: (a) => a.projectType !== undefined,
      validation: { maxLength: 2000 },
    },

    // ── Section 8: Contact ──
    {
      id: 'contactName',
      step: 18,
      title: 'Your name',
      inputType: 'text',
      bucket: 'contact',
      placeholder: 'Jane Smith',
      condition: (a) => a.projectType !== undefined,
      validation: { required: true },
    },
    {
      id: 'contactEmail',
      step: 19,
      title: 'Your email',
      description: 'We will send the report here.',
      inputType: 'text',
      bucket: 'contact',
      placeholder: 'jane@email.com',
      condition: (a) => a.projectType !== undefined,
      validation: { required: true },
    },
    {
      id: 'contactPhone',
      step: 20,
      title: 'Your phone number',
      description: 'Optional, but helps us reach you faster.',
      inputType: 'text',
      bucket: 'contact',
      placeholder: '(302) 555-1234',
      condition: (a) => a.contactEmail !== undefined,
    },
    {
      id: 'preferredContact',
      step: 21,
      title: 'How do you prefer to be contacted?',
      inputType: 'radio',
      bucket: 'contact',
      condition: (a) => a.contactEmail !== undefined,
      options: [
        { value: 'email', label: 'Email' },
        { value: 'phone', label: 'Phone call' },
        { value: 'text', label: 'Text message' },
        { value: 'either', label: 'Either is fine' },
      ],
      validation: { required: true },
    },
    {
      id: 'bestTime',
      step: 22,
      title: 'When is the best time to reach you?',
      inputType: 'radio',
      bucket: 'contact',
      condition: (a) => a.preferredContact !== undefined,
      options: [
        { value: 'morning', label: 'Mornings (8am–12pm)' },
        { value: 'afternoon', label: 'Afternoons (12pm–5pm)' },
        { value: 'evening', label: 'Evenings (5pm–8pm)' },
        { value: 'anytime', label: 'Anytime' },
      ],
      validation: { required: true },
    },
  ],
};
